(deftheme emacs-potpourri
  "Created 2017-06-28.")

(custom-theme-set-faces
 'emacs-potpourri
 '(default ((t (:family "Ubuntu Mono" :foundry "DAMA" :width normal :height 151 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#F8F8F2" :background "#2E2B2C" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#f8f8f0"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t nil)))
 '(escape-glyph ((t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#C491C4"))))
 '(highlight ((t (:foreground "#000000" :background "#ffe792"))))
 '(region ((t (:foreground "#ffffff" :background "#ED1153"))))
 '(shadow ((t (:foreground "#A9A3A3"))))
 '(secondary-selection ((t (:background "#ED1153"))))
 '(trailing-whitespace ((t (:background "#ED1153"))))
 '(font-lock-builtin-face ((t (:foreground "#C491C4"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#A9A3A3"))))
 '(font-lock-constant-face ((t (:foreground "#ED1153"))))
 '(font-lock-doc-face ((t (:foreground "#AfA7A7"))))
 '(font-lock-function-name-face ((t (:foreground "#B866FA"))))
 '(font-lock-keyword-face ((t (:foreground "#F76ACB"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#F76ACB"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#B866FA"))))
 '(font-lock-type-face ((t (:inherit (quote default)))))
 '(font-lock-variable-name-face ((t (:foreground "#C491C4"))))
 '(font-lock-warning-face ((t (:foreground "#f8f8f0" :background "#B866FA"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#B866FA"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:inherit (default)))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:background "#4E4B4C" :foreground "#F8F8F2" :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color "grey40" :style nil) :foreground "grey80" :background "grey30" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#000000" :background "#B866FA"))))
 '(isearch-fail ((t (:foreground "#f8f8f0" :background "#ED1153"))))
 '(lazy-highlight ((t (:foreground "#000000" :background "#ffe792"))))
 '(match ((t (:foreground "#000000" :background "#ffe792"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'emacs-potpourri)
